### ISSUE TITLE
Is this library "terser internal"?

### ISSUE THREAD

**Issue by connor4312** [jridgewell/source-map#3]
Hi,

I work on VS Code's JavaScript debugger. I happened to notice this dependency get pulled in when we updated Terser, and its promise of better memory and performance characteristics over Mozilla's `source-map` library is attractive!

This library implements a subset of the API of the full source-map library. I was interested to know what you view as the scope of this repo and its dependencies. Are you focused primarily on its consumption within Terser? If there are features a debugger might need that Terser is uninterested in, would they still be merged into these packages?

**Comment by jridgewell** [comment]
If Mozilla's API's aren't a exposed publicly in your implementation, I'd recommend using `@jridgewell/trace-mapping` or `@jridgewell/gen-mapping` directly, because whatever bundler you're using to package can likely tree-shake unused features. If the API is publicly exposed, then using `@jridgewell/source-map` is appropriate.

As for the goal, I intend for this to be a wrapper around the other two projects. Both already implement a similar API, but they take their instance as the first parameter to module-level functions instead of using a prototype method and `this`. I'm happy to accept any contributions to match Mozilla's API in this project and the others, as long as the implementation lives in the other repos and we only wrap the feature here. Any feature in the other repos should be designed in a way that makes them fast, light, and tree-shakeable.

I really should have made this a mono-repo...

**Comment by jridgewell** [comment]
See also https://github.com/jridgewell/source-map/pull/2, which is stalled on me adding a feature to `@jridgewell/resolve-uri`. 😬

**Comment by connor4312** [comment]
Thanks, I think that answers my questions!
