### ISSUE TITLE
`package.json` missing `types` in `exports`

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [jridgewell/source-map#4]
I noticed that `package.json` for this project doesn't have `types` set in (the "." property of) `exports`, which caused my typescript project to complain with `"strict": true` and `"skipLibCheck": false` because it couldn't find the types. Your other packages like `gen-mapping` do seem to have it, but I guess it was never added to this one :)

**Comment by damianaiamad** [comment]
This is causing compilation error for me.

`node_modules/terser/tools/terser.d.ts:3:77 - error TS7016: Could not find a declaration file for module '@jridgewell/source-map'. '/Users/damian/EventSoft/Code/precision/precise-harmony/node_modules/@jridgewell/source-map/dist/source-map.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/jridgewell__source-map` if it exists or add a new declaration (.d.ts) file containing `declare module '@jridgewell/source-map';`

3 import { SectionedSourceMapInput, EncodedSourceMap, DecodedSourceMap } from '@jridgewell/source-map';`

Using typescript@4.9.5, triggered by changing "moduleResolution" to "node16". Typescript is able to see typings with     "moduleResolution": "node". So might also be argued as a bug in typescript.

Also fixed by hacking @jridgewell/source-map/packages.json to include types in export property as noted by @ehoogeveen-medweb.

**Comment by ehoogeveen-medweb** [comment]
Just in case, @jridgewell do you get notified about new issues on this repo? I apologize if you're just busy, but I wanted to check since I had another issue get fixed after a long time and the author indicated that they hadn't actually noticed the activity on their repo.

**Comment by jridgewell** [comment]
Sorry, this is related to https://github.com/jridgewell/trace-mapping/pull/24. I just got an answer there, so I'll try to get to fixing this this week.

**Comment by jridgewell** [comment]
Fixed by 768d3486c5eeee3d1f98aec5fd3c403d31b0feb9
