### ISSUE TITLE
Any plans to add `SourceNode`?

### ISSUE THREAD

**Issue by SimenB** [jridgewell/source-map#8]
It's the last export from `source-map`.

```sh-session
$ node -p 'Object.keys(require("source-map"))'
[ 'SourceMapGenerator', 'SourceMapConsumer', 'SourceNode' ]
```

In Jest we only use it for a single test (https://github.com/jestjs/jest/blob/ce6a1d13bbb411af692e148fedbf331ac35f399d/e2e/coverage-handlebars/transform-handlebars.js), so no biggie from my side. But if added, all of the top level exports of the original library would be replicated 🙂

**Comment by jridgewell** [comment]
Not at the moment. It'd be pretty easy to generate a sectioned source map from the `SourceNode`s like that, but I don't really like the API it provides. It'd be much better to have a tagged template API that you compose a full map without worrying individual "node" mappings.

But in your case, it's really simple to generate by hand:

```js
function makeOffset(code: string) {
  const lines = code.split('\n');
  return { line: lines.length, column: lines.pop()!.length }
}

const sections = [];
let code = '';

code += 'const Handlebars = require("handlebars/dist/cjs/handlebars.runtime.js");\n';
code += 'module.exports = Handlebars.template(';

sections.push({
  offset: makeOffset(code),
  map: pc.map,
});
code += pc.code;

code += ');\n';

const map = {
  version: 3,
  sections,
};
```

**Comment by SimenB** [comment]
Cheers, thanks! Makes sense if the API is a bit clunky 🙂

**Comment by jridgewell** [comment]
I just published [@jridgewell/build-mapping](https://www.npmjs.com/package/@jridgewell/build-mapping) using a tagged template API. If you want to generate pretty source code with indentation, might I recommend [string-dedent](https://www.npmjs.com/package/string-dedent)?

```js
exports.process = (code, filename) => {
  const pc = Handlebars.precompile(code, {srcName: filename});
  const out = dedent(build)`
    const Handlebars = require("handlebars/dist/cjs/handlebars.runtime.js");
    module.exports = Handlebars.template(${pc});
  `;
  return { code: out.code, map: encodedMap(new AnyMap(out.map)) };
};

**Comment by SimenB** [comment]
Ooooh, nice! This is awesome - thank you for all the work you're doing 👍 

And yeah, I used `dedent` when adapting the code snippet you sent above (but ditched it as it was so much more code). But using `build-mapping` looks very nice

**Comment by SimenB** [comment]
Best thing is that it works quite a bit better! 😅 The current approach gives

<img width="640" alt="image" src="https://github.com/jridgewell/source-map/assets/1404810/6ae6e072-e8cd-4406-9519-938f52bcb0ca">

While the new library gives

<img width="624" alt="image" src="https://github.com/jridgewell/source-map/assets/1404810/f5a7b4c5-39b5-4406-a319-52279a88da78">

It's still a bit off, but that might be the babel plugin inserting odd istanbul statements afterwards. Adding another test which hits the `else` case gives

<img width="626" alt="image" src="https://github.com/jridgewell/source-map/assets/1404810/8835268b-56ed-4a61-bf3d-756337e843b9">

Which should hit all branches. Anyways - way better than it was, and no more `source-map` dependency (other than through `source-map-support`)! 🎉

**Comment by jridgewell** [comment]
> I used `dedent` when adapting the code snippet you sent above (but ditched it as it was so much more code).

If you don't want to use `dedent`, it's not necessary. The output code will still function fine without it, it'll just be (slightly) weirdly indented. But, if `pc.code` had multiple lines, then it's already weirdly indented on the 2nd+ lines.

> It's still a bit off, but that might be the babel plugin inserting odd istanbul statements afterwards. Adding another test which hits the else case gives

The `pc` map [looks good](https://evanw.github.io/source-map-visualization/#MjEzMwB7IjEiOmZ1bmN0aW9uKGNvbnRhaW5lcixkZXB0aDAsaGVscGVycyxwYXJ0aWFscyxkYXRhKSB7CiAgICByZXR1cm4gIiAgbW9ybmluZ1xuIjsKfSwiMyI6ZnVuY3Rpb24oY29udGFpbmVyLGRlcHRoMCxoZWxwZXJzLHBhcnRpYWxzLGRhdGEpIHsKICAgIHJldHVybiAiICBldmVuaW5nXG4iOwp9LCJjb21waWxlciI6WzgsIj49IDQuMy4wIl0sIm1haW4iOmZ1bmN0aW9uKGNvbnRhaW5lcixkZXB0aDAsaGVscGVycyxwYXJ0aWFscyxkYXRhKSB7CiAgICB2YXIgc3RhY2sxLCBoZWxwZXIsIGFsaWFzMT1kZXB0aDAgIT0gbnVsbCA/IGRlcHRoMCA6IChjb250YWluZXIubnVsbENvbnRleHQgfHwge30pLCBsb29rdXBQcm9wZXJ0eSA9IGNvbnRhaW5lci5sb29rdXBQcm9wZXJ0eSB8fCBmdW5jdGlvbihwYXJlbnQsIHByb3BlcnR5TmFtZSkgewogICAgICAgIGlmIChPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwocGFyZW50LCBwcm9wZXJ0eU5hbWUpKSB7CiAgICAgICAgICByZXR1cm4gcGFyZW50W3Byb3BlcnR5TmFtZV07CiAgICAgICAgfQogICAgICAgIHJldHVybiB1bmRlZmluZWQKICAgIH07CgogIHJldHVybiAiPHA+R29vZFxuIgogICAgKyAoKHN0YWNrMSA9IGxvb2t1cFByb3BlcnR5KGhlbHBlcnMsImlmIikuY2FsbChhbGlhczEsKGRlcHRoMCAhPSBudWxsID8gbG9va3VwUHJvcGVydHkoZGVwdGgwLCJhbSIpIDogZGVwdGgwKSx7Im5hbWUiOiJpZiIsImhhc2giOnt9LCJmbiI6Y29udGFpbmVyLnByb2dyYW0oMSwgZGF0YSwgMCksImludmVyc2UiOmNvbnRhaW5lci5wcm9ncmFtKDMsIGRhdGEsIDApLCJkYXRhIjpkYXRhLCJsb2MiOnsic291cmNlIjoiZ3JlZXQuaGJzIiwic3RhcnQiOnsibGluZSI6OCwiY29sdW1uIjowfSwiZW5kIjp7ImxpbmUiOjEyLCJjb2x1bW4iOjd9fX0pKSAhPSBudWxsID8gc3RhY2sxIDogIiIpCiAgICArIGNvbnRhaW5lci5lc2NhcGVFeHByZXNzaW9uKCgoaGVscGVyID0gKGhlbHBlciA9IGxvb2t1cFByb3BlcnR5KGhlbHBlcnMsIm5hbWUiKSB8fCAoZGVwdGgwICE9IG51bGwgPyBsb29rdXBQcm9wZXJ0eShkZXB0aDAsIm5hbWUiKSA6IGRlcHRoMCkpICE9IG51bGwgPyBoZWxwZXIgOiBjb250YWluZXIuaG9va3MuaGVscGVyTWlzc2luZyksKHR5cGVvZiBoZWxwZXIgPT09ICJmdW5jdGlvbiIgPyBoZWxwZXIuY2FsbChhbGlhczEseyJuYW1lIjoibmFtZSIsImhhc2giOnt9LCJkYXRhIjpkYXRhLCJsb2MiOnsic291cmNlIjoiZ3JlZXQuaGJzIiwic3RhcnQiOnsibGluZSI6MTMsImNvbHVtbiI6MH0sImVuZCI6eyJsaW5lIjoxMywiY29sdW1uIjo4fX19KSA6IGhlbHBlcikpKQogICAgKyAiITwvcD4iOwp9LCJ1c2VEYXRhIjp0cnVlfQovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247Y2hhcnNldD11dGYtODtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnpiM1Z5WTJWeklqcGJJbWR5WldWMExtaGljeUpkTENKdVlXMWxjeUk2VzEwc0ltMWhjSEJwYm1keklqb2lRVUZCUVN4TFFVOVZPMEZCUVVFN1FVRkJRU3hEUVZCV0xFdEJVMUU3UVVGQlFUdEJRVUZCTEVOQlZGSXNhME5CUzBVN1FVRkJRVHRCUVVGQk8wRkJRVUU3UVVGQlFUdEJRVUZCTzBGQlFVRTdRVUZCUVR0QlFVRkJPMEZCUVVFc1JVRkZSaXgzUkVGQlRTeDFSRUZCVGl4blQwRkdSVHRCUVVGQkxFVkJUMFlzYzBaQlFVVXNlVVJCUVVZc1owZEJURUVzVFVGTFFTdzBTVUZRUlR0QlFVRkJMRVZCVDAwc1dVRlFUanRCUVVGQkxFTkJURVlpTENKemIzVnlZMlZ6UTI5dWRHVnVkQ0k2V3lKN2V5RmNiaUFxSUVOdmNIbHlhV2RvZENBb1l5a2dUV1YwWVNCUWJHRjBabTl5YlhNc0lFbHVZeTRnWVc1a0lHRm1abWxzYVdGMFpYTXVYRzRnS2x4dUlDb2dWR2hwY3lCemIzVnlZMlVnWTI5a1pTQnBjeUJzYVdObGJuTmxaQ0IxYm1SbGNpQjBhR1VnVFVsVUlHeHBZMlZ1YzJVZ1ptOTFibVFnYVc0Z2RHaGxYRzRnS2lCTVNVTkZUbE5GSUdacGJHVWdhVzRnZEdobElISnZiM1FnWkdseVpXTjBiM0o1SUc5bUlIUm9hWE1nYzI5MWNtTmxJSFJ5WldVdVhHNTlmVnh1UEhBK1IyOXZaRnh1ZTNzamFXWWdZVzE5ZlZ4dUlDQnRiM0p1YVc1blhHNTdlMlZzYzJWOWZWeHVJQ0JsZG1WdWFXNW5YRzU3ZXk5cFpuMTlYRzU3ZTI1aGJXVjlmU0U4TDNBK0lsMTk1MzcAeyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImdyZWV0LmhicyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxLQU9VO0FBQUE7QUFBQSxDQVBWLEtBU1E7QUFBQTtBQUFBLENBVFIsa0NBS0U7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsRUFFRix3REFBTSx1REFBTixnT0FGRTtBQUFBLEVBT0Ysc0ZBQUUseURBQUYsZ0dBTEEsTUFLQSw0SUFQRTtBQUFBLEVBT00sWUFQTjtBQUFBLENBTEYiLCJzb3VyY2VzQ29udGVudCI6WyJ7eyFcbiAqIENvcHlyaWdodCAoYykgTWV0YSBQbGF0Zm9ybXMsIEluYy4gYW5kIGFmZmlsaWF0ZXMuXG4gKlxuICogVGhpcyBzb3VyY2UgY29kZSBpcyBsaWNlbnNlZCB1bmRlciB0aGUgTUlUIGxpY2Vuc2UgZm91bmQgaW4gdGhlXG4gKiBMSUNFTlNFIGZpbGUgaW4gdGhlIHJvb3QgZGlyZWN0b3J5IG9mIHRoaXMgc291cmNlIHRyZWUuXG59fVxuPHA+R29vZFxue3sjaWYgYW19fVxuICBtb3JuaW5nXG57e2Vsc2V9fVxuICBldmVuaW5nXG57ey9pZn19XG57e25hbWV9fSE8L3A+Il19), and the built map also [looks good](https://evanw.github.io/source-map-visualization/#MjI2OQBjb25zdCBIYW5kbGViYXJzID0gcmVxdWlyZSgiaGFuZGxlYmFycy9kaXN0L2Nqcy9oYW5kbGViYXJzLnJ1bnRpbWUuanMiKTsKbW9kdWxlLmV4cG9ydHMgPSBIYW5kbGViYXJzLnRlbXBsYXRlKHsiMSI6ZnVuY3Rpb24oY29udGFpbmVyLGRlcHRoMCxoZWxwZXJzLHBhcnRpYWxzLGRhdGEpIHsKICAgIHJldHVybiAiICBtb3JuaW5nXG4iOwp9LCIzIjpmdW5jdGlvbihjb250YWluZXIsZGVwdGgwLGhlbHBlcnMscGFydGlhbHMsZGF0YSkgewogICAgcmV0dXJuICIgIGV2ZW5pbmdcbiI7Cn0sImNvbXBpbGVyIjpbOCwiPj0gNC4zLjAiXSwibWFpbiI6ZnVuY3Rpb24oY29udGFpbmVyLGRlcHRoMCxoZWxwZXJzLHBhcnRpYWxzLGRhdGEpIHsKICAgIHZhciBzdGFjazEsIGhlbHBlciwgYWxpYXMxPWRlcHRoMCAhPSBudWxsID8gZGVwdGgwIDogKGNvbnRhaW5lci5udWxsQ29udGV4dCB8fCB7fSksIGxvb2t1cFByb3BlcnR5ID0gY29udGFpbmVyLmxvb2t1cFByb3BlcnR5IHx8IGZ1bmN0aW9uKHBhcmVudCwgcHJvcGVydHlOYW1lKSB7CiAgICAgICAgaWYgKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChwYXJlbnQsIHByb3BlcnR5TmFtZSkpIHsKICAgICAgICAgIHJldHVybiBwYXJlbnRbcHJvcGVydHlOYW1lXTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuIHVuZGVmaW5lZAogICAgfTsKCiAgcmV0dXJuICI8cD5Hb29kXG4iCiAgICArICgoc3RhY2sxID0gbG9va3VwUHJvcGVydHkoaGVscGVycywiaWYiKS5jYWxsKGFsaWFzMSwoZGVwdGgwICE9IG51bGwgPyBsb29rdXBQcm9wZXJ0eShkZXB0aDAsImFtIikgOiBkZXB0aDApLHsibmFtZSI6ImlmIiwiaGFzaCI6e30sImZuIjpjb250YWluZXIucHJvZ3JhbSgxLCBkYXRhLCAwKSwiaW52ZXJzZSI6Y29udGFpbmVyLnByb2dyYW0oMywgZGF0YSwgMCksImRhdGEiOmRhdGEsImxvYyI6eyJzb3VyY2UiOiJncmVldC5oYnMiLCJzdGFydCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJlbmQiOnsibGluZSI6MTIsImNvbHVtbiI6N319fSkpICE9IG51bGwgPyBzdGFjazEgOiAiIikKICAgICsgY29udGFpbmVyLmVzY2FwZUV4cHJlc3Npb24oKChoZWxwZXIgPSAoaGVscGVyID0gbG9va3VwUHJvcGVydHkoaGVscGVycywibmFtZSIpIHx8IChkZXB0aDAgIT0gbnVsbCA/IGxvb2t1cFByb3BlcnR5KGRlcHRoMCwibmFtZSIpIDogZGVwdGgwKSkgIT0gbnVsbCA/IGhlbHBlciA6IGNvbnRhaW5lci5ob29rcy5oZWxwZXJNaXNzaW5nKSwodHlwZW9mIGhlbHBlciA9PT0gImZ1bmN0aW9uIiA/IGhlbHBlci5jYWxsKGFsaWFzMSx7Im5hbWUiOiJuYW1lIiwiaGFzaCI6e30sImRhdGEiOmRhdGEsImxvYyI6eyJzb3VyY2UiOiJncmVldC5oYnMiLCJzdGFydCI6eyJsaW5lIjoxMywiY29sdW1uIjowfSwiZW5kIjp7ImxpbmUiOjEzLCJjb2x1bW4iOjh9fX0pIDogaGVscGVyKSkpCiAgICArICIhPC9wPiI7Cn0sInVzZURhdGEiOnRydWV9KTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2NoYXJzZXQ9dXRmLTg7YmFzZTY0LGV5SjJaWEp6YVc5dUlqb3pMQ0p1WVcxbGN5STZXMTBzSW5OdmRYSmpaWE1pT2xzaVozSmxaWFF1YUdKeklsMHNJbk52ZFhKalpYTkRiMjUwWlc1MElqcGJJbnQ3SVZ4dUlDb2dRMjl3ZVhKcFoyaDBJQ2hqS1NCTlpYUmhJRkJzWVhSbWIzSnRjeXdnU1c1akxpQmhibVFnWVdabWFXeHBZWFJsY3k1Y2JpQXFYRzRnS2lCVWFHbHpJSE52ZFhKalpTQmpiMlJsSUdseklHeHBZMlZ1YzJWa0lIVnVaR1Z5SUhSb1pTQk5TVlFnYkdsalpXNXpaU0JtYjNWdVpDQnBiaUIwYUdWY2JpQXFJRXhKUTBWT1UwVWdabWxzWlNCcGJpQjBhR1VnY205dmRDQmthWEpsWTNSdmNua2diMllnZEdocGN5QnpiM1Z5WTJVZ2RISmxaUzVjYm4xOVhHNDhjRDVIYjI5a1hHNTdleU5wWmlCaGJYMTlYRzRnSUcxdmNtNXBibWRjYm50N1pXeHpaWDE5WEc0Z0lHVjJaVzVwYm1kY2JudDdMMmxtZlgxY2JudDdibUZ0WlgxOUlUd3ZjRDRpWFN3aWJXRndjR2x1WjNNaU9pSTdjVU5CUVVFc1MwRlBWVHRCUVVGQk8wRkJRVUVzUTBGUVZpeExRVk5STzBGQlFVRTdRVUZCUVN4RFFWUlNMR3REUVV0Rk8wRkJRVUU3UVVGQlFUdEJRVUZCTzBGQlFVRTdRVUZCUVR0QlFVRkJPMEZCUVVFN1FVRkJRVHRCUVVGQkxFVkJSVVlzZDBSQlFVMHNkVVJCUVU0c1owOUJSa1U3UVVGQlFTeEZRVTlHTEhOR1FVRkZMSGxFUVVGR0xHZEhRVXhCTEUxQlMwRXNORWxCVUVVN1FVRkJRU3hGUVU5TkxGbEJVRTQ3UVVGQlFTeERRVXhHSWl3aWFXZHViM0psVEdsemRDSTZXMTE5NTU1AHsidmVyc2lvbiI6MywibmFtZXMiOltdLCJzb3VyY2VzIjpbImdyZWV0LmhicyJdLCJzb3VyY2VzQ29udGVudCI6WyJ7eyFcbiAqIENvcHlyaWdodCAoYykgTWV0YSBQbGF0Zm9ybXMsIEluYy4gYW5kIGFmZmlsaWF0ZXMuXG4gKlxuICogVGhpcyBzb3VyY2UgY29kZSBpcyBsaWNlbnNlZCB1bmRlciB0aGUgTUlUIGxpY2Vuc2UgZm91bmQgaW4gdGhlXG4gKiBMSUNFTlNFIGZpbGUgaW4gdGhlIHJvb3QgZGlyZWN0b3J5IG9mIHRoaXMgc291cmNlIHRyZWUuXG59fVxuPHA+R29vZFxue3sjaWYgYW19fVxuICBtb3JuaW5nXG57e2Vsc2V9fVxuICBldmVuaW5nXG57ey9pZn19XG57e25hbWV9fSE8L3A+Il0sIm1hcHBpbmdzIjoiO3FDQUFBLEtBT1U7QUFBQTtBQUFBLENBUFYsS0FTUTtBQUFBO0FBQUEsQ0FUUixrQ0FLRTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxFQUVGLHdEQUFNLHVEQUFOLGdPQUZFO0FBQUEsRUFPRixzRkFBRSx5REFBRixnR0FMQSxNQUtBLDRJQVBFO0FBQUEsRUFPTSxZQVBOO0FBQUEsQ0FMRiIsImlnbm9yZUxpc3QiOltdfQ==).

I think it's just that the output code is weird because it's a basically an interpreter, and inserting instanbul statements in the usual places doesn't really cover it.
